version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongodb:
    image: mongo
    container_name: filterdb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost

volumes:
  kafka_data:
  mongodb_data: