server:
  port: 9010

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    metadata-map:
      serviceId: inventory-service
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/